### ISSUE TITLE
Files not saving

### ISSUE THREAD

**Issue by xeryax** [robmarkcole/HASS-Deepstack-object#100]
I cant get this to save files with bounding boxes--- Heres my config.
`image_processing:
  - platform: deepstack_object
    ip_address: 192.168.100.4
    port: 80
    save_file_folder: /config/www/detector/deepstack/fyard/
    save_timestamped_file: True
    source:
      - entity_id: camera.frontyard
        name: frontYard_personChecker`

I'm no coder by any stretch..., but I noticed that the number of arguments in image_processing.py the save_image function (declared on line 194) doesnt match the call on line 190... 
Im not getting any errors at all, and the detection "seems" to be working fine, but I just can't view the boxes/verify what it is seeing.

**Comment by robmarkcole** [comment]
In python, class methods are implicitly passed `self`.
Please confirm the dir `/config/www/detector/deepstack/fyard/` exists. I see you are on docker, so paths may be different.
Please raise this question on the forums, rather than creating issues. 
Thanks
