### ISSUE TITLE
Detection endpoint not activated

### ISSUE THREAD

**Issue by SurfingSpider** [robmarkcole/HASS-Deepstack-object#104]
What does this error mean??

`2020-02-13 23:39:41 ERROR (SyncWorker_1) [custom_components.deepstack_object.image_processing] Deepstack error : Error from Deepstack: Detection endpoint not activated`

(FYI I am running docker on an Ubuntu virtual machine running on virtualbox) 

I get it in my HA log when I try and do a scan. I had it working intermittently with the avx version but them tried the noavx version now I cant get either to work. Both say they are activated if i go to the activation web-page. and I am only running one docker container at a time.

If I run it on a windows 10 machine it works. If I could run it without having to manually start it each time and have it full screen all the time I would be happy with that.

Any ideas?

**Comment by robmarkcole** [comment]
I cannot diagnose the reason but it appears the service is not running correctly. Your setup sounds overly complex, why not just run in docker on windows? Since this is not an actual issue with the code I will close this issue and suggest continuing the conversation on the deepstack forum.
Cheers

**Comment by SurfingSpider** [comment]
Ok I will scratch my head and think on. Thank you.

I already have hassio running as a VM on virtual box on my server. And
installing docker desktop stopped virtual box working. It enabled
hyper-visior which stops virtual box working.

I am starting to think I need to spend the cash and get a coral usb stick.

**Comment by robmarkcole** [comment]
Yes I think docker desktop uses virtualbox under the hood. Docker is a mixed blessing
