### ISSUE TITLE
How does one use the new multiple target feature?

### ISSUE THREAD

**Issue by ksheyman** [robmarkcole/HASS-Deepstack-object#106]
So I apologize if this is something simple or already covered but I just can't figure it out. How does one make use of the new multiple target feature? It does not create a new entity for the additional targets so where does that data go? When I read about this in the release notes I assumed that each new target would create a new image_processing entity. Is the only way to use this feature to listen for the deepstack.object_detected event and parse it out? If so, what does that feature do that wasn't already possible?

**Comment by robmarkcole** [comment]
Ive updated the readme to make the usage clearer
