### ISSUE TITLE
Timestamp in Filename - Colon bad for SMB/Windows

### ISSUE THREAD

**Issue by weltmeyer** [robmarkcole/HASS-Deepstack-object#107]
Hi, it seems like the filename for timestamped files is not best for SMB/Windows users:
Bad Chars are:  \/:*?"<>|

can we replace the colon by something different? Like an underscore?

I cant read it currently in SMB:
![image](https://user-images.githubusercontent.com/1668465/75872226-15695880-5e0e-11ea-858c-c0dec71901f1.png)

**Comment by robmarkcole** [comment]
to add:
```python
def get_valid_filename(name: str) -> str:
    return re.sub(r"(?u)[^-\w.]", "", str(name).strip().replace(" ", "_"))
```
