### ISSUE TITLE
Filename always says _Person_ even if it has detected a cat

### ISSUE THREAD

**Issue by weltmeyer** [robmarkcole/HASS-Deepstack-object#108]
Event shows it detected a cat,
it also clearly marks a cat with >90 confidence.

But Filename  is "deepstack_test_detector1_latest_person", in the file, the cat is marked :)

Config:

>     - platform: deepstack_object
>       ip_address: 10.0.0.123
>       port: 5000
>       #api_key: Mysecretkey
>       scan_interval: 1000 # Optional, in seconds
>       save_file_folder: /config/snapshots/
>       save_timestamped_file: True
>       target:
>         - person
>         - car
>         - cat
>         - mouse
>         - dog
>       source:
>         - entity_id: camera.katzenklappe2
>           name: deepstack_test_detector1

**Comment by rbflurry** [comment]
This has to do with this line here. It is using Target[0] which in your case is the first target you have in the config.
https://github.com/robmarkcole/HASS-Deepstack-object/blob/e9ce502803a4718f42d624d07ae9d35c35764771/custom_components/deepstack_object/image_processing.py#L222

**Comment by rbflurry** [comment]
I changed that line to this. Can you see if that works for you?
`        latest_save_path = directory + "{}_latest_{}.jpg".format(self._name, prediction["label"])`

**Comment by weltmeyer** [comment]
jepp. also made the timestamped file ONE file per target and fixed the filename issue on windows.

> def save_image(self, image, predictions, target, directory):
>         """Save a timestamped image with bounding boxes around targets."""
>         
> 
>         for prediction in predictions:
>             img = Image.open(io.BytesIO(bytearray(image))).convert("RGB")
>             draw = ImageDraw.Draw(img)
>             prediction_confidence = ds.format_confidence(prediction["confidence"])
>             if (
>                 prediction["label"] in target
>                 and prediction_confidence >= self._confidence
>             ):
>                 box = get_box(prediction, self._image_width, self._image_height)
>                 draw_box(
>                     draw,
>                     box,
>                     self._image_width,
>                     self._image_height,
>                     text=str(prediction_confidence),
>                     color=RED,
>                 )
>                 latest_save_path = directory + "{}_latest_{}.jpg".format(self._name, prediction["label"])
>                 img.save(latest_save_path)
>                 if self._save_timestamped_file:
>                     timestamp_save_path = directory + "{}_{}_{}.jpg".format(
>                     self._name, prediction["label"], self._last_detection.replace(":","_")
>                     )
> 
>                     out_file = open(timestamp_save_path, "wb")
>                     img.save(out_file, format="JPEG")
>                     out_file.flush()
>                     os.fsync(out_file)
>                     out_file.close()
>                     self.fire_saved_file_event(timestamp_save_path)
>                     _LOGGER.info("Saved bounding box image to %s", timestamp_save_path)

**Comment by robmarkcole** [comment]
Will just drop the target name
