### ISSUE TITLE
Deepstack suddenly stops working

### ISSUE THREAD

**Issue by Malogna** [robmarkcole/HASS-Deepstack-object#112]
`Deepstack error : Connection error: HTTPConnectionPool(host='10.0.0.100', port=5000): Max retries exceeded with url: /v1/vision/detection (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0fbe31ce10>: Failed to establish a new connection: [Errno 111] Connection refused'))`

I got this error randomly a few hours after i started making some automations in HA. I tried restarting the docker, the host and yes, the :5000 webpage is available.

**Comment by robmarkcole** [comment]
Please raise on the deepstack forum
