### ISSUE TITLE
[Feature request]  ROI for each camera?

### ISSUE THREAD

**Issue by rajeevan** [robmarkcole/HASS-Deepstack-object#139]
Hello,

First of all; thank you for writing this plugin and I'm loving it! It saves a lot of False-Notification from sent to mobile with all the tree and shadow movements 👍 

It would be good to have ROI for each camera instead of 1 ROI; now i have to setup multiple image processing to separate ROI. 

Thanks

**Comment by robmarkcole** [comment]
You can do this by configuring multiple entities (i.e. complete config per single camera). We can figure out a nicer way to do this for multiple cameras in the future

**Comment by robmarkcole** [comment]
Replaced by https://github.com/robmarkcole/HASS-Deepstack-object/issues/180
