### ISSUE TITLE
[Feature request] Confidence per object

### ISSUE THREAD

**Issue by salleq** [robmarkcole/HASS-Deepstack-object#140]
Unless I've understood something wrong, right now the confidence option affects all selected targets.

It would be great to set wanted confidence level for different objects. Say, for a person it could be as high as 87% to get minimal false detections, but for a small **bird** it might have to be as low as 50% to get detections done (and still not really have false detections).

**Comment by robmarkcole** [comment]
This is a good suggestion. Code would get complex, requires thought how best to implement it

**Comment by robmarkcole** [comment]
The solution right now is to configure multiple entities, with 1 entity per object & confidence combo.

**Comment by robmarkcole** [comment]
I think this is important to address since we know that the default object model is trained with a strong bias to detect people. It makes sense we would want to set a confidence per class which then overrides the default. e.g.
```yaml
targets:
  - class: person
     confidence: 87 # %
  - class: bird
     confidence: 50
```

**Comment by robmarkcole** [comment]
@salleq this is now implemented on `master` branch, can you try it out?

**Comment by robmarkcole** [comment]
It would simplify the code to make `confidence` required for configured targets

**Comment by robmarkcole** [comment]
Done in https://github.com/robmarkcole/HASS-Deepstack-object/releases/tag/4.0
