### ISSUE TITLE
[Feature request] Image path/name on event

### ISSUE THREAD

**Issue by JanickGers85** [robmarkcole/HASS-Deepstack-object#143]
It would be super-cool to have the name of the image on event, it is really useful expecially when you ask for timestamped image output and handy to send notification with image listening only to deepstack events.

{
    "event_type": "deepstack.object_detected",
    "data": {
        "bounding_box": {
            "height": 0.586,
            "width": 0.271,
            "y_min": 0.208,
            "x_min": 0.642,
            "y_max": 0.794,
            "x_max": 0.913
        },
        "box_area": 0.159,
        "centroid": {
            "x": 0.778,
            "y": 0.501
        },
        "name": "person",
        "confidence": 99.772,
        "entity_id": "XXXXX",
        **"image-path": "/image/xxxxxx-2020_08_21_20-18-07.jpg"**
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-21T20:18:07.133941+00:00",
    "context": {
        "id": "6cdb1a79e3eb11ea8627b9076e6b9fda",
        "parent_id": null,
        "user_id": null
    }
}

**Comment by JanickGers85** [comment]
@robmarkcole I did it "badly" by myself, surely can be done better, I can't push my feature branch nor do a PR toward master since I do not have permissions.

![GitExtensions_2020-08-28_23-31-24](https://user-images.githubusercontent.com/21289907/91616810-c6e4e300-e986-11ea-903a-0f75986ecc9c.png)

**Comment by robmarkcole** [comment]
Covered by https://github.com/robmarkcole/HASS-Deepstack-object/issues/168
