### ISSUE TITLE
Home Assistant Example Automation

### ISSUE THREAD

**Issue by Finagain** [robmarkcole/HASS-Deepstack-object#146]
The example automation says to use "object: person" but I had to use "name: person" as that is what is showing in my fired event object under data.

current example:
- action:
  - data_template:
      title: "New object detection"
      message: "{{ trigger.event.data.name }} with confidence {{ trigger.event.data.confidence }}"
    service: notify.pushbullet
  alias: Object detection automation
  condition: []
  id: '1120092824622'
  trigger:
  - platform: event
    event_type: deepstack.object_detected
    event_data:
      **object: person <- I changed to name: person**

My fired event:
"event_type": "deepstack.object_detected",
    "data": {
        "bounding_box": {
            "height": 0.333,
            "width": 0.251,
            "y_min": 0.267,
            "x_min": 0.663,
            "y_max": 0.6,
            "x_max": 0.914
        },
        "box_area": 0.084,
        "centroid": {
            "x": 0.788,
            "y": 0.433
        },
        **"name": "car"**,
        "confidence": 96.152,
        "entity_id": "image_processing.deepstack_object_driveway"
    },

**Comment by robmarkcole** [comment]
duplicates https://github.com/robmarkcole/HASS-Deepstack-object/issues/145
