### ISSUE TITLE
 [name] is an invalid option 

### ISSUE THREAD

**Issue by fgonza2** [robmarkcole/HASS-Deepstack-object#147]
the "name:" option as mentioned on the readme doesn't work.   

it gives me the following error:

 Invalid config for [image_processing.deepstack_object]: [name] is an invalid option for [image_processing.deepstack_object]. Check: image_processing.deepstack_object->name. (See ?, line ?). 

if i remove it it clears and it works.   is this a known issue?   on 0.115.3

**Comment by jazzmonger** [comment]
Interesting.  My setup (working fir months) stopped working 6-8 weeks ago.  Changing object: to name: for the return value solved it.

See my analysis here:

https://community.home-assistant.io/t/deepstack-automation-not-firing-consistently/212856/18?u=jazzmonger

**Comment by robmarkcole** [comment]
@fgonza2 I guess they dropped it in an HA release, did you see any mentions in release notes?

@jazzmonger we updated the readme on that point
