### ISSUE TITLE
[Feature request] ROI diagonally settings

### ISSUE THREAD

**Issue by Cavekeeper** [robmarkcole/HASS-Deepstack-object#151]
Not all properties are rectangular as the ROI settings suggest. It would make sense to be able to adjust the ROI diagonally as well. See example photo.
![ROI diagonally](https://user-images.githubusercontent.com/61421138/99255937-f16f6b00-2814-11eb-8bb1-42803e2c0fa8.png)

**Comment by koldogut** [comment]
Define custom motion areas as in Unifi Protect will be a plus:

![image](https://user-images.githubusercontent.com/43078880/99261517-1ff14400-281d-11eb-98c2-76bb15524502.png)

**Comment by robmarkcole** [comment]
Again this is functionality that we want to see image_processing on home assistant implement

**Comment by robmarkcole** [comment]
OK this is something I want to explore in this integration, allowing ROI that are not just a box, but also other basic shapes. This solution could then be contributed back to HA

**Comment by robmarkcole** [comment]
@koldogut does Unifi Protect output a file that represents the ROI

**Comment by robmarkcole** [comment]
Replacing with https://github.com/robmarkcole/HASS-Deepstack-object/issues/184

**Comment by robmarkcole** [comment]
@koldogut can you give me a link to their docs?

**Comment by koldogut** [comment]
Unifi Protect is not open-source, so no technical documents are available to deep-dive in motion zones function. Check this out anyway to have an idea, 

[https://help.ui.com/hc/en-us/articles/360056987954-UniFi-Protect-Manage-motion-detection-and-privacy-zones#:~:text=To%20set%20up%20a%20motion,dragging%20them%20with%20your%20cursor.](url)
