### ISSUE TITLE
Error while setting up deepstack_object platform for image_processing

### ISSUE THREAD

**Issue by Justahobby01** [robmarkcole/HASS-Deepstack-object#157]
Just updated to version 3.5 and also updated HA to version 2020.12.1. Rolling back to v3.4 appears to fix it.

Supervisor Version  2020.12.

Home Assistant 2020.12.1

```Logger: homeassistant.components.image_processing
Source: custom_components/deepstack_object/image_processing.py:216
Integration: Image processing (documentation, issues)
First occurred: 3:12:29 PM (6 occurrences)
Last logged: 3:12:29 PM

Error while setting up deepstack_object platform for image_processing
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deepstack_object/image_processing.py", line 170, in setup_platform
    object_entity = ObjectClassifyEntity(
  File "/config/custom_components/deepstack_object/image_processing.py", line 216, in __init__
    self._dsobject = ds.DeepstackObject(
TypeError: __init__() takes from 3 to 5 positional arguments but 6 were given```

**Comment by juan11perez** [comment]
Similar issue. 3.5 doesnt load for me. 3.4 works normal.
Home Assistant 2020.12.1
core on docker.

**Comment by robmarkcole** [comment]
Checkout latest release and make sure Deepstack-python depdency is updated

**Comment by juan11perez** [comment]
Tried it; I'm running docker and confirm it has deepstack-python==0.8 but the component doesn't load.
run this debugger "homeassistant.components.image_processing: debug"
and got the following:

`2020-12-20 14:26:42 ERROR (MainThread) [homeassistant.components.image_processing] Error while setting up deepstack_object platform for image_processing
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deepstack_object/image_processing.py", line 170, in setup_platform
    object_entity = ObjectClassifyEntity(
  File "/config/custom_components/deepstack_object/image_processing.py", line 216, in __init__
    self._dsobject = ds.DeepstackObject(
TypeError: __init__() takes from 3 to 5 positional arguments but 6 were given`

**Comment by robmarkcole** [comment]
@juan11perez what is your config?

**Comment by juan11perez** [comment]
good day.

`- platform: deepstack_object
  ip_address: 192.168.1.100
  port: 5000
  # api_key: !secret deepstack_key
  timeout: 10
  save_file_folder: /config/www/image_processing/tmp/
  save_timestamped_file: true
  # roi_x_min: (optional, default 0), range 0-1, must be less than roi_x_max
  # roi_x_max: (optional, default 1), range 0-1, must be more than roi_x_min
  # roi_y_min: (optional, default 0), range 0-1, must be less than roi_y_max
  # roi_y_max: (optional, default 1), range 0-1, must be more than roi_y_min  
  targets:
  - person
  - car
  # - truck
  confidence: 80
  source:
  - entity_id: camera.saved_images
    name: deepstack_object `

**Comment by robmarkcole** [comment]
Also are you using Deepstack face as well?

**Comment by juan11perez** [comment]
yes and it's working well.
this is face config:

```
- platform: deepstack_face
  ip_address: 192.168.1.100
  port: 5000
  # api_key: !secret deepstack_key
  timeout: 10
  save_file_folder: /config/www/image_processing/faces/
  save_timestamped_file: True  
  detect_only: false
  source:
  - entity_id: camera.saved_images
    name: deepstack_face  
```

**Comment by robmarkcole** [comment]
There is a dependency conflict

https://github.com/robmarkcole/HASS-Deepstack-face/issues/25

**Comment by juan11perez** [comment]
Thank you; so for now stay with deepstack_object 3.4 as it works fine

**Comment by robmarkcole** [comment]
I will update here when it's ready to try latest. This is only an issue for people using both object and face. I need to merge these two soon

**Comment by juan11perez** [comment]
Thank you very much for your help and explanation

**Comment by robmarkcole** [comment]
OK the face integration is updated and this should no longer be an issue

**Comment by juan11perez** [comment]
I have now updated both components to latest release and they both work fine.
Thank you for your prompt reply.
