### ISSUE TITLE
Error: [homeassistant.components.image_processing] Error on receive image from entity: Unable to get image

### ISSUE THREAD

**Issue by neutrongenious** [robmarkcole/HASS-Deepstack-object#194]
I have followed your guide and configured Deepstack-object against my camera.
Automation has been configured to trigger scan upon motion detection.
after trigger I am getting the following in the log:
` 2021-01-13 22:13:46 WARNING (MainThread) [homeassistant.helpers.entity] Update of image_processing.deepstack_object_antaresincsantry_entrance_hd is taking over 10 seconds
2021-01-13 22:13:46 ERROR (MainThread) [homeassistant.components.image_processing] Error on receive image from entity: Unable to get image `

**Comment by robmarkcole** [comment]
This is an issue with your camera, not this integration. 
Suggest searching the main HA forums
Thanks
