### ISSUE TITLE
Default target not respected

### ISSUE THREAD

**Issue by danbayliss** [robmarkcole/HASS-Deepstack-object#195]
I've been using Deepstack for a while with no target set in configuration.yaml as the default was Person and that's all I needed. I've updated to the latest version and it seems to be detecting cars too so I think the default target of just person isn't the case anymore.

I've fixed this by adding it to configuration.yaml but wanted to let you know so you can either resolve in the code or update the Readme

**Comment by robmarkcole** [comment]
Thanks @danbayliss this is a legit issue.

When no target is set, the default target of `person` is listed but the state then includes all objects above the default target `confidence`:

![image](https://user-images.githubusercontent.com/11855322/104561415-47a73180-563f-11eb-9d76-76c2b5ecc9c0.png)

**Comment by robmarkcole** [comment]
@danbayliss please checkout master. If all is good I will do a release

**Comment by danbayliss** [comment]
@robmarkcole Just installed master and can confirm it's fixed. Thanks
