### ISSUE TITLE
Summary of targets

### ISSUE THREAD

**Issue by RicoRehn** [robmarkcole/HASS-Deepstack-object#205]
Hi,
First thank you for a good integration! I use this for all my outside cams to be able to detect different objects and run automation.
This may not classify as an issue but in your previous version I used the 'ALL car count' to be able to do automations depending on how many cars it detects, in the last version this is gone. Is there any other way to achieve this summary?
I could create multiple image_proccessing on the same cam and different targets but that seems like a bad approach. 

Best Regards
Rickard

**Comment by robmarkcole** [comment]
Yes generating this summary list got a bit more complicated since there can now be a confidence per class, so I could not use the same function as previously. I see the benefit of this summary and will add it back

**Comment by robmarkcole** [comment]
https://github.com/robmarkcole/HASS-Deepstack-object/releases/tag/v4.2
