### ISSUE TITLE
New error since recent update, changed nothing in config

### ISSUE THREAD

**Issue by ksheyman** [robmarkcole/HASS-Deepstack-object#208]
Since the last update, I am getting this error:

```
2021-01-25 09:07:01 ERROR (MainThread) [homeassistant.components.image_processing] Error while setting up deepstack_object platform for image_processing
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/deepstack_object/image_processing.py", line 221, in setup_platform
object_entity = ObjectClassifyEntity(
File "/config/custom_components/deepstack_object/image_processing.py", line 271, in __init__
self._dsobject = ds.DeepstackObject(
TypeError: __init__() got an unexpected keyword argument 'ip'
2021-01-25 09:07:01 ERROR (MainThread) [homeassistant.components.imag
```

my config is: 

``` 
  - platform: deepstack_object
    ip_address: 192.168.1.197
    port: 5000
    api_key: !secret deepstack
    save_file_folder: /config/www/deepstack/
    save_timestamped_file: True
    targets: 
      target: person
    confidence: 80    
    source:
      - entity_id: camera.living_room_me
        name: people_in_living_room  
```
I changed nothing. Not sure what to try here since the only appearance of 'ip' is in 'ip_address' which is still referenced in the docs as a valid config field.

edit: forgot to include info

I'm running HA on Docker
supervisor-2021.01.7
core-2021.1.5

This issue started with Deepstack Object v4.2, but I rolled back to 4.1 and 4.0 and its the same problem. Wondering if this could be related to whatever changes were made to HA/HACS to fix the recent security vulnerabilities? No reason to suspect that other than timing though.

**Comment by robmarkcole** [comment]
My only guess is that maybe your dependency `deepstack-python` has not been updated, please check which version you have installed

**Comment by ksheyman** [comment]
> My only guess is that maybe your dependency `deepstack-python` has not been updated, please check which version you have installed

I apologize, I've looked everywhere I can think of and can't figure out how to check that. Would that be in my HA container or my Deepstack container?

**Comment by robmarkcole** [comment]
In HA. Some people had this issue when they had both deepstack face and object integrations but mismatched versions. SInce this is not a code issue please continue discussion on HA forum

**Comment by ksheyman** [comment]
Thanks, will do.

**Comment by Dysannl** [comment]
> Thanks, will do.

Hi there, did you fix it? i've got the same issue ?
