### ISSUE TITLE
Not an issue: Question/Inspiration

### ISSUE THREAD

**Issue by greberg** [robmarkcole/HASS-Deepstack-object#210]
Hi

First of all, a brilliant custom component that work really well. So my question that I'm not really sure how to fix. I have an automation that notify me if a car is on the garage driveway. This works perfect, the problem occurs  when that car parks on the driveway. Then every new scan will publish a new notification until the car is gone again which of course is not the preferred way. Question would be, how to solve this kind of setup. I like to get the notification but I just want it to come with new cars. any super good idea? :-)

Thanks in advance

**Comment by robmarkcole** [comment]
you can just create a binary sensor in HA and use an automation to change its state, then send the notification on that

Please create a discussion on this. Closing
