### ISSUE TITLE
Deepstack Instance Behind Reverse Proxy (HTTPS)

### ISSUE THREAD

**Issue by n8detar** [robmarkcole/HASS-Deepstack-object#217]
Not sure if this is possible but could you add the ability to send requests to a Deepstack instance that is behind a reverse proxy with https? When attempting this I get the following error in the home assistant log:
`Deepstack error : Error from Deepstack request, status code 400`
I have the ip configured to be the url without https:// (deepstack.example.com) and the port to be 443. I tested using the curl command to confirm whether it works behind the reverse proxy and it works as expected so I'm assuming it might be possible to enable this functionality in this component.

**Comment by robmarkcole** [comment]
This is quite a niche request. If you can create a pull request showing how to address this that would be very helpful/essential

**Comment by n8detar** [comment]
> 
> 
> This is quite a niche request. If you can create a pull request showing how to address this that would be very helpful/essential

I figured it would be pretty niche. I came up with a better option (site to site VPN) so I no longer need this.
