### ISSUE TITLE
Depstack error : Error from Deepstack request, status code: 401

### ISSUE THREAD

**Issue by koldogut** [robmarkcole/HASS-Deepstack-object#220]
After upgrading Deepstack (docker container) with latest version I'm getting error 401 (unauthorized). Deepstack GUI web service says it's already activated and cameras (Unifi Protect) have annonymous access enabled. Any ideas?

**Comment by koldogut** [comment]
Solved!, by any reason it seems that now Deepstack is taking the API key seriously. After some testing with older versions I've just included it in every Deepstack object defined and back to business!

**Comment by markmghali** [comment]
Thank you! I was having the same issue after upgrading! I didn't realize we needed the api key in HASS Config.
