### ISSUE TITLE
No version key in Manifest

### ISSUE THREAD

**Issue by RicoRehn** [robmarkcole/HASS-Deepstack-object#232]
Hi,

I get this Warning in HA.

"WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'deepstack_object'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'deepstack_object'"

Home assistant core 2021.4 require this version key, can you supply us with a new update for this? 
Thank you.

Br
Rickard

**Comment by robmarkcole** [comment]
Did you update? The key exists here https://github.com/robmarkcole/HASS-Deepstack-object/blob/2d3319984fea01166cdbf3e52511c350ace7d7dd/custom_components/deepstack_object/manifest.json#L5

**Comment by RicoRehn** [comment]
Ah sorry, i thought i had latest version. After update it worked..
Thanks..
