### ISSUE TITLE
Outdated custom components and integrations might break in Home Assistant Core 2021.6

### ISSUE THREAD

**Issue by calleman** [robmarkcole/HASS-Deepstack-object#245]
Hi,

I had trouble loading my image_processing entity after a fixed my cameras. It turned out that it wouldnt load until I set a "version" in the manifest file. Easy peasy but as it is now it will never work with newer versions of HA.

Thanks for an outstanding component!

https://home-assistant-guide.com/2021/06/02/outdated-custom-components-and-integrations-might-break-in-home-assistant-core-2021-6/

**Comment by FuzzyMistborn** [comment]
This is already in the manifest.json.  Make sure you're running the latest version.

https://github.com/robmarkcole/HASS-Deepstack-object/blob/1c12f05971cc9e46f33d149ca033370dd3a3290c/custom_components/deepstack_object/manifest.json#L5

**Comment by calleman** [comment]
Hi,

Im sorry, I updated to the latest version but must have missed to actually do so! Thanks!
