### ISSUE TITLE
Unable to find referenced entities camera.xxxx

### ISSUE THREAD

**Issue by tonfa80** [robmarkcole/HASS-Deepstack-object#248]
Hi,

Object recognition works via python test script when trying it but I cannot get it working in HA 2021.7.3.

Following warning appears in log when testing with image_processing.scan

```
Logger: homeassistant.helpers.service
Source: helpers/service.py:128 
First occurred: 17.03.56 (1 occurrences) 
Last logged: 17.03.56

Unable to find referenced entities camera.xxxx
```

Local file camera is defined:
```
- platform: local_file
  file_path: /config/snapshots/deepstack_object_local_file_latest.jpg
```

Could someone help what is going wrong.

**Comment by tonfa80** [comment]
Found the issue.. It was my mistake.

**Comment by WarDrake** [comment]
What was the mistake?

**Comment by Draxter** [comment]
@tonfa80 What was the issue, I'm getting the same error and the entity with tha tname definitely exists.

**Comment by tonfa80** [comment]
If I remember correctlt it was some fundamental issue when calling camera entity(?) in maybe image_processing.yaml(?) I wish I would remember it better...

**Comment by Draxter** [comment]
> 
> 
> If I remember correctlt it was some fundamental issue when calling camera entity(?) in maybe image_processing.yaml(?) I wish I would remember it better...

You mean in the [image_processing.py](https://github.com/robmarkcole/HASS-Deepstack-object/blob/master/custom_components/deepstack_object/image_processing.py) ?

**Comment by tonfa80** [comment]
No, it was on my yaml configuration file

**Comment by Draxter** [comment]
I figured it out. My service call was wrong, I passed a camera entity into it, instead of image_processing entity. it should have been:
```
service: image_processing.scan
target:
  entity_id: image_processing.deepstack_object_local_file
```

**Comment by WarDrake** [comment]
Awesome! thanks for the solution guys.
