### ISSUE TITLE
HA has removed HTTP Error Codes which breaks this component

### ISSUE THREAD

**Issue by robbrad** [robmarkcole/HASS-Deepstack-object#255]
@robmarkcole : See

https://github.com/home-assistant/core/pull/58380/commits/fbb7c3136847a42339965614013e7a7014fb946b

There is a PR that's been merged to dev that's broken this component

**Comment by robmarkcole** [comment]
@robbrad thanks for the alert. This is a small PR to put the variables into this codebase, unless these have simply moved in HA?

**Comment by robbrad** [comment]
HA now imports a library of http statuses instead of constants. 

I went to do the same in your code but realised you don’t actually use them here, so removed. (I think you moved them to the deep stack Python module?)

maybe you need them there instead?

**Comment by robmarkcole** [comment]
Yes they are there already, so I think this is a non issue:

https://github.com/robmarkcole/deepstack-python/blob/c5b51eef3b8cd8e1a6386c75a83fc9c4260f36e6/deepstack/core.py#L16

**Comment by robbrad** [comment]
Yeh it broke my CICD action when I tried to do a config check on my HA - it said it could not import the const when the custom component loaded https://github.com/home-assistant/core/pull/58380

**Comment by robbrad** [comment]
https://github.com/robbrad/HA-Config/runs/4169993696?check_suite_focus=true

Failed config
  General Errors: 
    - Platform error image_processing.deepstack_object - cannot import name 'HTTP_BAD_REQUEST' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
    - Platform error image_processing.deepstack_object - cannot import name 'HTTP_BAD_REQUEST' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
    - Platform error image_processing.deepstack_object - cannot import name 'HTTP_BAD_REQUEST' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
    - Platform error image_processing.deepstack_object - cannot import name 'HTTP_BAD_REQUEST' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
    - Platform error image_processing.deepstack_object - cannot import name 'HTTP_BAD_REQUEST' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
    - Platform error image_processing.deepstack_object - cannot import name 'HTTP_BAD_REQUEST' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
    - Platform error image_processing.deepstack_object - cannot import name 'HTTP_BAD_REQUEST' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by robmarkcole** [comment]
OK I see these are imported but not used:

```
    HTTP_BAD_REQUEST,
    HTTP_OK,
    HTTP_UNAUTHORIZED,
```

so a simple PR to remove these will suffice

**Comment by robbrad** [comment]
PR is in :)
