### ISSUE TITLE
docker error on running in jetson xavier nx

### ISSUE THREAD

**Issue by VikaashBalaji** [robmarkcole/HASS-Deepstack-object#259]
I am running the below command on jetson xavier nx development kit
docker run -e VISION-DETECTION=True -e API-KEY="mysecretkey" -v localstorage:/datastore -p 80:5000 deepquestai/deepstack

I get the below mentioned error.
standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by robmarkcole** [comment]
please ask on deepstack forum
