### ISSUE TITLE
Is it possible to run deepstack using my custom model in frigate container.

### ISSUE THREAD

**Issue by AnishDeepak** [robmarkcole/HASS-Deepstack-object#269]
Hi,  according to my requirement, I need to detect the objects that are not there in frigate maplabel.txt. So I have been trying to run my custom model in frigate but it not working. Is it possible to run deepstack in container which was created for frigate.

**Comment by robmarkcole** [comment]
I dont know your reasons for requiring a single container - deepstack exposes an API which I assume frigate could query

**Comment by robmarkcole** [comment]
no reply
