### ISSUE TITLE
Confidence on saved images is too small

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-Deepstack-object#39]
Need to increase the size of the text as its nearly impossible to read

**Comment by rbflurry** [comment]
I looked into this a little bit. It looks like you have to specify a font to do so? are there fonts included in Homeassistant already?

**Comment by robmarkcole** [comment]
I think I need to merge saving images into HA and ass you say allow HA to handle formatting correctly

**Comment by robmarkcole** [comment]
Not handled in this CC
