### ISSUE TITLE
Consider how to support multiple cameras

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-Deepstack-object#42]
From @lmamakos
`
It’d also be nice to be able to either specify a path for each camera, or to include the camera 
name in the saved file. If I have multiple cameras going, I think it would be neat to have a file camera set up showing the latest image from each camera. Right now, the same “latest” file is overwritten by each configured camera.
`

Right now the solution is to configure the integration separately for each camera, so you specify a different save folder. You suggestion here might be better. However I also am considering whether the functionality of saving images with bounding boxes should be pushed into the home assistant repo, as it can be shared with the tensorflow integration etc

**Comment by robmarkcole** [comment]
I think my preference is for horizontal scaling, so each configuration should be for a single camera only

**Comment by lmamakos** [comment]
I've moved to that model in my configuration, and it seems like a reasonable solution.

**Comment by robmarkcole** [comment]
This is the recommended approach
