### ISSUE TITLE
save_image method doesn't account for orientation

### ISSUE THREAD

**Issue by vlebourl** [robmarkcole/HASS-Deepstack-object#44]
Image orientation, usually contained in the exif data in jpg images can help determine image orientation to ensure it is save correctly.

See this thread for more details and potential solutions: https://stackoverflow.com/questions/4228530/pil-thumbnail-is-rotating-my-image/11543365#11543365

**Comment by vlebourl** [comment]
seems that HA handles images the same way you do. I opened a feature request, maybe you could add your vote? 
https://community.home-assistant.io/t/account-for-image-orientation-in-local-file-camera-componenet/130393

**Comment by robmarkcole** [comment]
Ok gave it a vote :)
As you say, this should be handled by the camera integration
Cheers
