### ISSUE TITLE
My installation not work

### ISSUE THREAD

**Issue by rabeliyo** [robmarkcole/HASS-Deepstack-object#45]
Hello, I have followed all the indications but I do not get the recognition to work.
I have entered the test photo in the save folder but it does not work.

My continuous container log :

./run: line 2:  5198 Aborted                 (core dumped) python3 /app/intelligence.py &> /dev/null
./run: line 2:  5213 Aborted                 (core dumped) python3 /app/intelligence.py &> /dev/null
./run: line 2:  5228 Aborted                 (core dumped) python3 /app/intelligence.py &> /dev/null
./run: line 2:  5241 Aborted                 (core dumped) python3 /app/intelligence.py &> /dev/null
./run: line 2:  5256 Aborted                 (core dumped) python3 /app/intelligence.py &> /dev/null

Awesome work!! Thanks

**Comment by rbflurry** [comment]
Use deepquestai/deepstack:noavx instead of deepquestai/deepstack
