### ISSUE TITLE
image_processing crashes docker when reaching scan_interval (GPU docker)

### ISSUE THREAD

**Issue by jaburges** [robmarkcole/HASS-Deepstack-object#47]
image_processing seems to send all entities at once to the docker container once `scan_interval` is reached. access via HA and curl confirms container no longer responds to queries

**Comment by jaburges** [comment]
i've raised an issue in the [deepstack forum](https://forum.deepstack.cc/t/multiple-object-detection-on-gpu-docker-no-response-from-container/114)

workaround is to set a very very high `scan_interval` but knowing that in that amount of time you'll need to reboot deepstack docker. 

Apparently other platforms can handle the simultaneous scan of multiple images, so thing this is a deepstack issue.

**Comment by robmarkcole** [comment]
Ok this is a deepstack issue. Really HA should be sending images for processing on update of the image, but a workaround is to stagger your scan_intervals so they dont coincide
