### ISSUE TITLE
Platform error: image_processing - Integration deepstack_object not found.

### ISSUE THREAD

**Issue by darox** [robmarkcole/HASS-Deepstack-object#57]
I have palced the image_processing.py file in custom_components, but HA throws the following error:
Log Details (ERROR)
Wed Oct 02 2019 18:55:18 GMT+0200 (Mitteleuropäische Sommerzeit)
Platform error: image_processing - Integration deepstack_object not found.

**Comment by robmarkcole** [comment]
@darox please try rebooting your device. Sometimes restarting the home assistant process is not enough to ensure install of requirements

**Comment by darox** [comment]
@robmarkcole You mean the host? I'm running HA in docker and already restarted the container.

**Comment by robmarkcole** [comment]
Hmm that should have done it, certainly worked with Hassio on the pi in past. You could try pulling the container image afresh

**Comment by darox** [comment]
I just re-deployed the HA container. Btw: if I bash into the HA container the image_processing.py file is located at:
bash-5.0# pwd
/config/custom_components
bash-5.0# ls
google_fit           image_processing.py
should be fine right?

**Comment by robmarkcole** [comment]
That is incorrect, please see the readme, TLDR all contents including manifest.json are required

**Comment by darox** [comment]
Doesn't help:
bash-5.0# pwd
/config/custom_components
bash-5.0# ls
__init__.py          __pycache__          image_processing.py  manifest.json

**Comment by robmarkcole** [comment]
the files should be within `custom_components/deepstack_object/`

**Comment by darox** [comment]
This was definitely my fault sorry. It sets up now, but person are not recognized. Deepstack works with curl test. My config is:
`image_processing:
  - platform: deepstack_object
    ip_address: 192.168.2.56
    port: 5000
    timeout: 5
    scan_interval: 20000
    save_file_folder: /config/www/deepstack_person_images
    target: person
    confidence: 50
    source:
      - entity_id: camera.waschzimmer
        name: person_detector
`

Should be ok right?

**Comment by robmarkcole** [comment]
Well you have a scan intervall of 20000 seconds, you should adjust that, as described in the docs.
Thanks

**Comment by darox** [comment]
It works now, thx for the great support!
