### ISSUE TITLE
How to identify changes of objects

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-Deepstack-object#79]
Object detection models return an object count, but what we `actually` care about is new objects - we want to ignore background. How could the integration do this? Ideas:
- learn background objects (static) and exclude them from detections?
- assisgn background objects an ID then ignore them, doe this by comparing adjacent images

**Comment by MTrab** [comment]
would it be possible to look at detection bounding-box?

I thought I could use this for detecting when a car arrives/departs from my garage. It works - somewhat, but when a car is parked in the garage it get detected (thus triggering image_processing.object_detected event every time) as long as it is present in the garage.

**Comment by robmarkcole** [comment]
In my other vision components the approach takes is to fire an `object_detected` event including the bounding box info. apply here

**Comment by robmarkcole** [comment]
This would really need to be implemented by deepstack or a standalone object tracking integration
