### ISSUE TITLE
Custom Updater

### ISSUE THREAD

**Issue by johntdyer** [robmarkcole/HASS-Deepstack-object#8]
Please add support for custom updater plugin for update tracking [link](https://github.com/custom-components/custom_updater)

**Comment by robmarkcole** [comment]
I am happy to review a PR for this

**Comment by robmarkcole** [comment]
custom updater is replaced by HACS which requires no changes to this repo

**Comment by aptonline** [comment]
I believe changes are still needed as per https://community.home-assistant.io/t/face-and-person-detection-with-deepstack-local-and-free/92041/233?u=apt

HACS keeps telling me there is a new version available even after update.

**Comment by SiliconAvatar** [comment]
> custom updater is replaced by HACS which requires no changes to this repo

That's not the case.

With HACS you are not allowed two custom components in the same repository. If you do, as is done here, HACS will only manage the first one.

Adding this repo to HACS only shows the face custom component and not the object component.

https://custom-components.github.io/hacs/developer/integration/

**Comment by robmarkcole** [comment]
@SiliconAvatar thanks for bringing that to my attention. I may have to refactor the codebase in that case, which will be required for eventual HA integration anyways. If you want to make a PR to add in support for `custom updater` that would be appreciated

**Comment by robmarkcole** [comment]
OK now split repo in 2 to support HACS
