### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by Malaga82** [robmarkcole/HASS-Deepstack-object#82]
Hello,
great stuff here!
I'm using an external VPS with the docker installation and seems to works fine.
I just wondering if there is an option to scan as later as possible to prevent upload every 10 secs.
I was thinking that the timeout option could to the trick but it seems to upload anyways every X seconds anyways.
I wish you can add an option or a long scan_interval so i can fire the service only when i trigger it.
Thanks

**Comment by jiiins** [comment]
just set `scan_interval` to a high enough number. I use 20000 seconds.

**Comment by Malaga82** [comment]
ah, `scan_interval` is available?!...i miss that!
Will try, thanks

**Comment by robmarkcole** [comment]
You can set a `scan_interval` in the component config and it will over-ride the built in value. 
Cheers
