### ISSUE TITLE
Timeout connecting to Deepstack but manual commands work.

### ISSUE THREAD

**Issue by rbflurry** [robmarkcole/HASS-Deepstack-object#84]
After a few days running I get this message in my logs and no further processing from deepstack.

```
Log Details (ERROR)
Mon Nov 11 2019 10:45:01 GMT-0500 (Eastern Standard Time)
Depstack error : Timeout connecting to Deepstack, current timeout is 10 seconds
```

I am running Hassio on a different host than deepstack. From the Hassio container console 

running curl -X POST -F image=@test/test-image3.jpg 'http://192.168.19.204:5000/v1/vision/detection' the command completes successfully. so communication between the two hosts works.

Do you have anything else I can try? Thank you.

**Comment by robmarkcole** [comment]
You can increase the timeout length, but it sounds like something is wrong

**Comment by robmarkcole** [comment]
This is likely not an issue with the code here
