### ISSUE TITLE
[Question]file output naming

### ISSUE THREAD

**Issue by Malaga82** [robmarkcole/HASS-Deepstack-object#85]
Hello, is it possible to naming output file like othe object detection extensions?
I mean, i use DOODS and TENSORFLOW and i just set:
`/config/www/public/{{ camera_entity.split('.')[1] }}_TENSORFLOW.jpg` to have just as many output file as my configured camera, without having many and many jpg around public folder.
Is it possible to have this behavior with deepstack by any means?
Thanks

**Comment by robmarkcole** [comment]
done in release v2.2
