### ISSUE TITLE
Remove space in timestamp

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-Deepstack-object#90]
You changed the timestamp in the .py like so “%Y-%m-%d %H:%M:%S” leaving a gap between date and time.
This provides an incomplete link and some messanger services (Gotify) cant complete and the picture doesnt pull through.
In your future release please add it back if possible.
Thank you.

**Comment by robmarkcole** [comment]
resolved in release 2.4

**Comment by juan11perez** [comment]
thank you very much.
