### ISSUE TITLE
image_processing.file_saved is never triggered

### ISSUE THREAD

**Issue by i00** [robmarkcole/HASS-Deepstack-object#92]
The image is saved but the event is never triggered

**Comment by robmarkcole** [comment]
Have you configured `save_file_folder: something` and `save_timestamped_file: True`?

**Comment by i00** [comment]
I didn't think save_timestamped_file would be needed? ... I mean shouldn't it just trigger this if it the file is overwritten?... I don't want millions of images saved!

**Comment by robmarkcole** [comment]
The event is only fired for timestamped files. Could add it for the `latest` image also, that is a feature request

**Comment by i00** [comment]
That would be great :) 👍
