### ISSUE TITLE
No module named 'homeassistant.util.pil

### ISSUE THREAD

**Issue by patrik996** [robmarkcole/HASS-Deepstack-object#94]
Got this error. The component has worked for me before.

Im on hass docker, version 0.101.3. Latest version of HASS-Deepstack-object. Tried removing the cache.

Platform error image_processing.deepstack_object - No module named 'homeassistant.util.pil'

**Comment by robmarkcole** [comment]
As per release notes HA >=0.103 is required. 
Thanks

**Comment by patrik996** [comment]
Thanks! Real rooky mistake :D
