### ISSUE TITLE
Used to work fine now has error with import draw_box

### ISSUE THREAD

**Issue by i00** [robmarkcole/HASS-Deepstack-object#96]
With the latest version of HA (0.103.5) I get this:
Platform error image_processing.deepstack_object - cannot import name 'draw_box' from 'homeassistant.components.image_processing' (/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py)

Any ideas?
Thanks

**Comment by robmarkcole** [comment]
Hi you need to update to the latest release. Thanks
